name: Sync LeetCode Solutions

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours
  workflow_dispatch:        # Allows manual run

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: "solutions"
          commit-message: "Sync LeetCode solutions"
